name: Kani Formal Verification Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  formal-verif-build:
    name: Formal Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Clean Cargo.toml for Kani
        run: |
          # Remove `cdylib` from targets in Cargo.toml because it confuses Kani
          sed '17d' Cargo.toml > Cargo.toml.new
          mv Cargo.toml.new Cargo.toml

      # Only ensure that Kani can build successfully
      - name: Kani Rust Verifier
        uses: model-checking/kani-github-action@v1.1
        with:
          args: --only-codegen